name: 'Analogicus Janeway Documentation Action'
description: 'This action generates jekyll docs'
branding:
  color: purple
  icon: layers

runs:
    using: 'composite'
    steps:
      - name: Checkout dependencies
        shell: bash
        run: |
          python3 -m pip install cicconf
          cicconf --rundir ../ --config config.yaml clone --https
      - name: Install cicsim
        shell: bash
        run:  python3 -m pip install cicsim
      - name: Run docs
        shell: bash
        run: |
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          export CIC_RANDOM_PLOTNAME=1
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/eda/lib
          export PATH=/opt/eda/bin:$HOME/.local/bin:$PATH
          rm -rf docs/ && cicsim template tech/docs/jekyll_docs_template.yaml options.yaml
